### ISSUE TITLE
Errors múltiples en neteja nocturna

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#205]
(1) S'ha de provar consulta de BBDD en un TEST (Veure enviafib\enviafib-persistence\src\test\java\es\caib\enviafib\persistence\test\TestPersistenceJPA.java )
(2) S'han de tenir Peticions de tot tipus i diferents estats

ERROR 1:

```
04:00:02,038 ERROR [es.caib.enviafib.logic.PeticioLogicaEJB] (EJB default - 4) Error en el proces d`eliminacio automatic de peticions de firma ja resoltes. Error en la peticio: null : null: java.lang.NumberFormatException: null
        at java.base/java.lang.Long.parseLong(Long.java:655)
        at java.base/java.lang.Long.parseLong(Long.java:817)
        at deployment.enviafib.ear.enviafib-ejb.jar//es.caib.enviafib.logic.PeticioLogicaEJB.eliminarPeticionsPortaFIB(PeticioLogicaEJB.java:1017)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.as.ee@7.2.8.GA-redhat-00002//org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:50)
        at org.jboss.as.ee@7.2.8.GA-redhat-00002//org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:61)
```

ERROR 2:

Nota: Com es que la selecció processa entrades amb cadena "ESBORRADA_*****" ?????

```
04:00:02,041 ERROR [es.caib.enviafib.logic.PeticioLogicaEJB] (EJB default - 4) Error en el proces d`eliminacio automatic de peticions de firma ja resoltes. Error en la peticio: ESBORRADA_284591 : For input string: "ESBORRADA_284591": java.lang.NumberFormatException: For input string: "ESBORRADA_284591"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Long.parseLong(Long.java:692)
        at java.base/java.lang.Long.parseLong(Long.java:817)
        at deployment.enviafib.ear.enviafib-ejb.jar//es.caib.enviafib.logic.PeticioLogicaEJB.eliminarPeticionsPortaFIB(PeticioLogicaEJB.java:1017)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.as.ee@7.2.8.GA-redhat-00002//org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:50)
        at org.jboss.as.ee@7.2.8.GA-redhat-00002//org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:61)
```

**Comment by fbosch-fundaciobit** [comment]
S'ha arreglat la QUERY per l'esborrat nocturn. El codi que filtrava era diferent del codi que s'escrivia a les peticions un cop ja esborrades, i per això no les reconeixia correctament:

![image](https://user-images.githubusercontent.com/40387703/190397173-a17dc55d-d7b4-431e-b7f7-24ec60c66ff6.png)
